apiVersion: v1
kind: Service
metadata:
  name: mysql-deploy
  labels:
    app: mysql-deployment
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: phonebook-webserver
