apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook-webserver
  template:
    metadata:
      labels:
        app: phonebook-webserver
    spec:
      containers:
        - image: yasinkartal/result_server
          name: resultserver-deploy
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE_HOST
          ports:
            - containerPort: 80
              name: pb-webserver
          resources: {}

